#!/bin/sh
exec scala "$0" "$@"
!#

object script extends App {
  val methods = for {
    file <- 'a' to 'h'
    rank <- '1' to '8'
  } yield s"def $file$rank: Square = unsafeFromAlgebraic(AlgebraicFile('$file'), AlgebraicRank($rank))"

  val content =
    s"""|// GENERATED by mk-SquareAbbr.sh - DO NOT MODIFY
        |
        |package eu.timepit.equites
        |package util
        |
        |import SquareUtil._
        |
        |object SquareAbbr {
        |  ${methods.mkString("\n  ")}
        |}""".stripMargin

  println(content)
}

script.main(args)
