#!/bin/sh
exec scala "$0" "$@"
!#

object script extends App {
  val methods = for {
    file <- 'a' to 'h'
    rank <- '1' to '8'
  } yield s"def $file$rank: Square = Square('$file', $rank)"

  println(
    s"""|// GENERATED by mk-SquareAbbr.sh - DO NOT MODIFY
        |
        |package eu.timepit.equites
        |package util
        |
        |object SquareAbbr {
        |  ${methods.mkString("\n  ")}
        |}""".stripMargin)
}

script.main(args)
